### ISSUE TITLE
Change iconv-corefoundation to be in `optionalDependencies`

### ISSUE THREAD

**Issue by mcmxcdev** [argv-minus-one/dmg-license#7]
See more: https://github.com/pnpm/pnpm/issues/3640

**Comment by argv-minus-one** [comment]
The dependency on iconv-corefoundation isn't actually optional. Dmg-license doesn't work at all without it. It's needed to convert input text into the Classic Mac OS character encodings expected in DMG license data.

I don't think that will help you anyway. Even if dmg-license did the character encoding conversion in some other, platform-independent way and didn't depend on iconv-corefoundation, dmg-license also requires the `hdiutil` program that only exists on macOS, so it still won't work on any other platform. For this reason, [the `package.json` for dmg-license says it requires macOS (`darwin`)](https://github.com/argv-minus-one/dmg-license/blob/bb949ee452eac69ca685c9caf4e4fb2f3568c91e/package.json#L76-L78), same as [the `package.json` for iconv-corefoundation](https://github.com/argv-minus-one/iconv-corefoundation/blob/09fc154a7af1717eed6bb329bed86334a61cd720/package.json#L27-L29).

~~I see that [electron-builder currently has a non-optional dependency on dmg-license](https://github.com/electron-userland/electron-builder/blob/1497411498e802ef97f735e9de4568d00e3f8659/package.json#L42-L43). I'm not sure why—unlike dmg-license, electron-builder *is* useful on platforms other than macOS—so you might want to ask them to make their dependency on dmg-license optional.~~

**Edit:** It looks like I was reading the wrong `package.json`. [Electron-builder depends on dmg-builder](https://github.com/electron-userland/electron-builder/blob/1497411498e802ef97f735e9de4568d00e3f8659/packages/electron-builder/package.json#L58), and [dmg-builder's dependency on dmg-license is optional](https://github.com/electron-userland/electron-builder/blob/1497411498e802ef97f735e9de4568d00e3f8659/packages/dmg-builder/package.json#L27-L28), which should be fine.

[People now seem to be saying that this is actually an issue with pnpm's dependency handling.](https://github.com/pnpm/pnpm/issues/3640#issuecomment-894190825) Shall I close this issue, then?

**Comment by mcmxcdev** [comment]
Thank you for the in-depth explanation!

Yes, the creator of pnpm confirmed it's related to their dependency handling, closing this ;)
