### ISSUE TITLE
packages including dmg-license become uninstallable on linux

### ISSUE THREAD

**Issue by airtonix** [argv-minus-one/dmg-license#8]
using pnpm, any project that ends up describing your packages as a dep becomes uninstallable.

**Comment by airtonix** [comment]
ugh... https://github.com/pnpm/pnpm/issues/3640

**Comment by zkochan** [comment]
Maybe we can fix it in pnpm, I am not sure.

But the issue is that `iconv-corefoundation` is not an optional dependency. Even though it supports only macOS.

**Comment by argv-minus-one** [comment]
@zkochan Dmg-license also supports only macOS. It needs not only iconv-corefoundation but also the `hdiutil` program that only exists on macOS. See https://github.com/argv-minus-one/dmg-license/issues/7#issuecomment-894857493 for details.
