### ISSUE TITLE
Dependabot alerts: ansi-regex is vulnerable to Inefficient Regular Expression Complexity

### ISSUE THREAD

**Issue by tm-sthm** [argv-minus-one/dmg-license#9]
Please update the affected packages.

Dependabot alerts: 
https://github.com/advisories/GHSA-93q8-gq69-wqmw

affected npm package:
cli-truncate@^1.1.0

**Comment by oliverschwendener** [comment]
Is `cli-truncate` even used? As far as I see it's specified in `package.json` but not used in the code, or am I missing something?

**Comment by argv-minus-one** [comment]
Done in release 1.0.10.
